create schema if not exists extensions;

drop table if exists public.speed_verifications cascade;
drop table if exists public.road_segments cascade;
drop table if exists public.vehicle_profiles cascade;
drop function if exists public.road_segments_near_route(jsonb, double precision);

drop extension if exists pgrouting;
drop extension if exists postgis cascade;

create extension postgis with schema extensions;
create extension pgrouting with schema extensions;

create table public.road_segments (
  id bigint generated by default as identity primary key,
  osm_id bigint,
  name text,
  highway_type text not null,
  maxspeed_mph numeric,
  oneway boolean,
  access text,
  lsv_status text not null default 'unknown'
    check (lsv_status in ('verified_eligible', 'restricted', 'unknown', 'verified_blocked')),
  speed_source text,
  speed_verified_at timestamptz,
  geom extensions.geometry(LineString, 4326) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index road_segments_geom_idx
  on public.road_segments using gist (geom);
create index road_segments_osm_id_idx
  on public.road_segments (osm_id);

create table public.speed_verifications (
  id bigint generated by default as identity primary key,
  road_segment_id bigint not null references public.road_segments(id) on delete cascade,
  source_name text not null,
  source_url text,
  posted_speed_mph numeric not null,
  verified_at timestamptz not null default now(),
  notes text
);

create index speed_verifications_road_segment_id_idx
  on public.speed_verifications (road_segment_id);

create table public.vehicle_profiles (
  id text primary key,
  name text not null,
  max_road_speed_mph numeric not null,
  description text
);

insert into public.vehicle_profiles (
  id, name, max_road_speed_mph, description
) values (
  'golf_cart_lsv',
  'Street-legal LSV',
  35,
  'California LSV baseline: roads posted 35 mph or less'
);

alter table public.road_segments enable row level security;
alter table public.speed_verifications enable row level security;
alter table public.vehicle_profiles enable row level security;

create policy "public can read road segments"
  on public.road_segments
  for select
  to anon, authenticated
  using (true);

create policy "public can read speed verifications"
  on public.speed_verifications
  for select
  to anon, authenticated
  using (true);

create policy "public can read vehicle profiles"
  on public.vehicle_profiles
  for select
  to anon, authenticated
  using (true);

grant select on public.road_segments to anon, authenticated;
grant select on public.speed_verifications to anon, authenticated;
grant select on public.vehicle_profiles to anon, authenticated;

create or replace function public.road_segments_near_route(
  route_geojson jsonb,
  max_distance_meters double precision default 30
)
returns table (
  id bigint,
  osm_id bigint,
  name text,
  highway_type text,
  maxspeed_mph numeric,
  oneway boolean,
  access text,
  lsv_status text,
  speed_source text,
  speed_verified_at timestamptz,
  distance_meters double precision
)
language sql
stable
set search_path = ''
as $$
  with route as (
    select
      extensions.st_setsrid(
        extensions.st_geomfromgeojson(route_geojson::text),
        4326
      ) as geom
  )
  select
    r.id,
    r.osm_id,
    r.name,
    r.highway_type,
    r.maxspeed_mph,
    r.oneway,
    r.access,
    r.lsv_status,
    r.speed_source,
    r.speed_verified_at,
    extensions.st_distance(r.geom::extensions.geography, route.geom::extensions.geography) as distance_meters
  from public.road_segments r
  cross join route
  where extensions.st_dwithin(
    r.geom::extensions.geography,
    route.geom::extensions.geography,
    max_distance_meters
  )
  order by distance_meters asc;
$$;

grant execute on function public.road_segments_near_route(jsonb, double precision)
  to anon, authenticated;
