create or replace function public.route_lsv_candidate(start_lon double precision,start_lat double precision,end_lon double precision,end_lat double precision,allow_unknown boolean default true,snap_max_distance_meters double precision default 500)
returns table(path_seq integer,edge_id bigint,edge_name text,edge_status text,maxspeed_mph numeric,length_m double precision,geom_geojson jsonb)
set search_path='extensions, public' language plpgsql stable as $$
declare start_node bigint; end_node bigint; graph_sql text; component_id bigint;
begin
 with sc as (select n.id,n.lsv_component,extensions.st_distance(n.geom::extensions.geography,extensions.st_setsrid(extensions.st_point(start_lon,start_lat),4326)::extensions.geography) d from public.road_nodes n where n.lsv_component is not null and extensions.st_dwithin(n.geom::extensions.geography,extensions.st_setsrid(extensions.st_point(start_lon,start_lat),4326)::extensions.geography,snap_max_distance_meters) order by n.geom operator(extensions.<->) extensions.st_setsrid(extensions.st_point(start_lon,start_lat),4326) limit 48), ec as (select n.id,n.lsv_component,extensions.st_distance(n.geom::extensions.geography,extensions.st_setsrid(extensions.st_point(end_lon,end_lat),4326)::extensions.geography) d from public.road_nodes n where n.lsv_component is not null and extensions.st_dwithin(n.geom::extensions.geography,extensions.st_setsrid(extensions.st_point(end_lon,end_lat),4326)::extensions.geography,snap_max_distance_meters) order by n.geom operator(extensions.<->) extensions.st_setsrid(extensions.st_point(end_lon,end_lat),4326) limit 48)
 select s.id,e.id,s.lsv_component into start_node,end_node,component_id from sc s join ec e on e.lsv_component=s.lsv_component order by s.d+e.d limit 1;
 if start_node is null or end_node is null then return; end if;
 graph_sql:=case when allow_unknown then format($g$select id,source_node_id source,target_node_id target,length_m cost,-1::double precision reverse_cost from public.road_edges where lsv_component=%L and lsv_status in ('verified_eligible','unknown') and (maxspeed_mph is null or maxspeed_mph<=35)$g$,component_id) else format($g$select id,source_node_id source,target_node_id target,length_m cost,-1::double precision reverse_cost from public.road_edges where lsv_component=%L and lsv_status='verified_eligible' and (maxspeed_mph is null or maxspeed_mph<=35)$g$,component_id) end;
 return query select p.path_seq::integer,e.id,e.name,e.lsv_status,e.maxspeed_mph,e.length_m,extensions.st_asgeojson(e.geom)::jsonb from extensions.pgr_dijkstra(graph_sql,start_node,end_node,true) p join public.road_edges e on e.id=p.edge where p.edge<>-1 order by p.path_seq;
end; $$;
