create table if not exists public.import_runs (
  id bigint generated by default as identity primary key,
  source_name text not null,
  source_url text,
  source_version text,
  bbox text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'running'
    check (status in ('running', 'completed', 'failed')),
  record_count integer not null default 0,
  notes text
);

alter table public.import_runs enable row level security;

drop policy if exists "public can read import runs" on public.import_runs;
create policy "public can read import runs"
  on public.import_runs
  for select
  to anon, authenticated
  using (true);

create table if not exists public.road_nodes (
  id bigint generated by default as identity primary key,
  osm_node_id bigint not null unique,
  geom extensions.geometry(Point, 4326) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists road_nodes_geom_gist
  on public.road_nodes
  using gist (geom);

create index if not exists road_nodes_osm_node_id_idx
  on public.road_nodes (osm_node_id);

alter table public.road_nodes enable row level security;

drop policy if exists "public can read road nodes" on public.road_nodes;
create policy "public can read road nodes"
  on public.road_nodes
  for select
  to anon, authenticated
  using (true);

create table if not exists public.road_edges (
  id bigint generated by default as identity primary key,
  osm_way_id bigint not null,
  osm_segment_index integer not null,
  direction text not null
    check (direction in ('forward', 'backward')),
  source_node_id bigint not null references public.road_nodes(id) on delete cascade,
  target_node_id bigint not null references public.road_nodes(id) on delete cascade,
  geom extensions.geometry(LineString, 4326) not null,
  length_m double precision not null check (length_m >= 0),
  name text,
  ref text,
  highway_type text not null,
  oneway boolean not null default false,
  maxspeed_mph numeric,
  maxspeed_forward_mph numeric,
  maxspeed_backward_mph numeric,
  maxspeed_conditional text,
  access text,
  vehicle text,
  motor_vehicle text,
  motorcar text,
  motorroad text,
  lsv_status text not null default 'unknown'
    check (lsv_status in ('verified_eligible', 'restricted', 'unknown', 'verified_blocked')),
  lsv_reason text,
  speed_source text,
  speed_verified_at timestamptz,
  import_run_id bigint references public.import_runs(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (osm_way_id, osm_segment_index, direction)
);

create index if not exists road_edges_source_node_idx
  on public.road_edges (source_node_id);

create index if not exists road_edges_target_node_idx
  on public.road_edges (target_node_id);

create index if not exists road_edges_osm_way_idx
  on public.road_edges (osm_way_id);

create index if not exists road_edges_geom_gist
  on public.road_edges
  using gist (geom);

create index if not exists road_edges_lsv_status_idx
  on public.road_edges (lsv_status);

create index if not exists road_edges_highway_type_idx
  on public.road_edges (highway_type);

create index if not exists road_edges_import_run_idx
  on public.road_edges (import_run_id);

alter table public.road_edges enable row level security;

drop policy if exists "public can read road edges" on public.road_edges;
create policy "public can read road edges"
  on public.road_edges
  for select
  to anon, authenticated
  using (true);

create table if not exists public.turn_restrictions (
  id bigint generated by default as identity primary key,
  osm_relation_id bigint not null unique,
  restriction_type text not null,
  from_way_id bigint not null,
  via_node_osm_id bigint,
  to_way_id bigint not null,
  except_modes text[],
  import_run_id bigint references public.import_runs(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists turn_restrictions_from_way_idx
  on public.turn_restrictions (from_way_id);

create index if not exists turn_restrictions_to_way_idx
  on public.turn_restrictions (to_way_id);

create index if not exists turn_restrictions_import_run_idx
  on public.turn_restrictions (import_run_id);

alter table public.turn_restrictions enable row level security;

drop policy if exists "public can read turn restrictions" on public.turn_restrictions;
create policy "public can read turn restrictions"
  on public.turn_restrictions
  for select
  to anon, authenticated
  using (true);